### PR TITLE
Add patches from Debian packaging

### PR DESCRIPTION
**Pull request by andrewshadura**
Hi,

Here are two patches produced in the Debian project, to support GNU/kFreeBSD system and using shared version of expat, including 1.95.

I'd be thankful if you merged them.

### CODE REVIEW

**Comment by andrewshadura** [comment]
What about the other patch?

**Comment by pointsman** [comment]
Re about the other patch: In fact I changed my mind quite a while ago and I'm willing to add a configure option to build against an external expat lib. (Not because I'm convinced, but this hasn't to be discussed here, I hope it is enough, that I'm willing to do it.)

But is there in fact any real need to support  expat 1.95.\* compatibility?

**Comment by andrewshadura** [comment]
I don't know. Currenly, expat in Debian is 2.1.0, so maybe it's no longer needed indeed.

**Comment by pointsman** [comment]
Added to trunk.

**Pull request closed without merging**
